[package]
name = "lichess-minecraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
tracing-subscriber = "0.3.16"
valence = { git = "https://github.com/valence-rs/valence" }
